// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
try {
  // Hanya gunakan dotenv jika tersedia (untuk development lokal)
  require("dotenv").config();
} catch (e) {
  // Abaikan di production karena Docker sudah menyuntikkan env secara langsung
}

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
};
